In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int32') # vectors R /lists Python

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # matrices
print(b)
#b[1,]
b[1,2]

[[9. 8. 7.]
 [6. 5. 4.]]


4.0

In [ ]:
# Get Dimension
#a.ndim
b.ndim

2

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # vectors R /lists Python
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[:, 2]

array([ 3, 10])

In [ ]:
#a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D matrix
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get a specific element (work outside in)
b[0,1,1]

4

In [ ]:
# replace
b[:,:,1] = [[9,9],[8,3]]
print(b)

[[[1 9]
  [3 9]]

 [[5 8]
  [7 3]]]


In [ ]:
# All 0s matrix
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(4,2)

array([[0.09335087, 0.31602518],
       [0.02639834, 0.08851198],
       [0.51672682, 0.32901658],
       [0.26460255, 0.53426334]])

In [ ]:
np.random.randint(-4,8, size=(3,3))

array([[ 1,  3,  3],
       [-4, -2,  6],
       [-2,  7, -2]])

In [ ]:
np.identity(5)

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


We want a 5 by 5 matrix with ones on the outer element, 0 on the inner elements and 9 in the center element


In [68]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
a = np.array([1,2,3])
b = a.copy() # deepcopy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [70]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [71]:
a+2

TypeError: can only concatenate list (not "int") to list

In [72]:
a-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [73]:
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
# ...
np.min(stats, axis=1)
# horizontal stack