<a href="https://colab.research.google.com/github/trprince21/STATS101C_notes/blob/main/Week0_Discussion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

In [16]:
#a = np.array([1,2,3], dtype='int32')
a = np.array([1,2,3]) # vectors R /lists Python
print(a)

[1 2 3]


In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # matrices (0th index -> first element)
print(b)
#b[1,]
b[1,2]

[[9. 8. 7.]
 [6. 5. 4.]]


4.0

In [19]:
# Get Dimension
#a.ndim
b.ndim

2

In [20]:
# Get Shape
b.shape

(2, 3)

In [21]:
# Get Type
a.dtype

dtype('int64')

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r, c]
a[1, 5]

13

In [27]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [28]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [29]:
#a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [30]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D matrix
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Get specific element (work outside in)
b[0,1,1]

4

In [34]:
# replace
b[:,:,1] = [[9,9],[8,8]]
#b[:,:,1] = [[9,9],[8,8,3]]
print(b)

[[[1 9]
  [3 9]]

 [[5 8]
  [7 8]]]


In [35]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [37]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [38]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
np.random.rand(4,2)

array([[0.50336039, 0.40891354],
       [0.34226534, 0.99260471],
       [0.3989767 , 0.4345736 ],
       [0.15355699, 0.00657888]])

In [40]:
np.random.randint(-4,8, size=(3,3))

array([[ 0,  1, -2],
       [-4, -1,  2],
       [ 7,  3,  1]])

In [41]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


We want a 5 by 5 matrix with ones on the outer elements, 0 on the inner elements, and 9 in the center element



In [43]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
a = np.array([1,2,3])
b = a.copy() # deepcopy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [45]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [46]:
a+2

array([3, 4, 5, 6])

In [47]:
a-2

array([-1,  0,  1,  2])

In [48]:
a*2

array([2, 4, 6, 8])

In [51]:
b = [1,2,3]
b+1

TypeError: can only concatenate list (not "int") to list

In [52]:
b*2

[1, 2, 3, 1, 2, 3]

In [53]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [54]:
b = np.array([1,0,1])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [56]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(stats)

1

In [60]:
np.max(stats, axis=1)

array([3, 6])

In [61]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [62]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [63]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [65]:
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
